server:
  port: ${HYPERPROF_PORT}
spring:
  datasource:
    username: ${HYPERPROF_DB_USER}
    password: ${HYPERPROF_DB_PASSWORD}
    url: jdbc:mysql://${HYPERPROF_DB_HOST}:${HYPERPROF_DB_PORT}/{HYPERPROF_DB_NAME}?serverTimezone=UTC
  jpa:
    show-sql: false
    properties:
      "[format_sql]": false

br:
  com:
    luankenzley:
      hyperprof:
        core:
          services:
            token:
              jjwt:
                accessTokenSigningKey: ${HYPERPROF_JJWT_ACCESS_TOKEN_SIGING_KEY}
                acessTokenExpirationInSeconds: ${HYPERPROF_JJWT_ACCESS_TOKEN_EXPIRATION_IN_SECONDS}
                refreshTokenSigningKey: ${HYPERPROF_JJWT_REFRESH_TOKEN_SIGING_KEY}
                refreshTokenExpirationInSeconds: ${HYPERPROF_JJWT_REFRESH_TOKEN_EXPIRATION_IN_SECONDS}